daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    js_shared_dict_zone zone=kv:1M timeout=3600s evict;

    server {
        listen 8888;

        js_var $rl_zone_name kv;
        js_var $rl_windows_ms 1000;
        js_var $rl_limit 5;
        js_var $rl_key $remote_addr;
        js_set $rl_result main.ratelimit;

        location / {
            if ($rl_result != "0") {
                add_header Retry-After $rl_result always;
                return 429 "Too Many Requests\n";
            }
            return 200 "OK\n";
        }

        location /status {
            return 200 "limit_result=$rl_result";
        }
    }
}
