daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    server {
        listen 8888;

        location / {
            js_content main.redirect;
        }

        location /a {
            js_content main.a;
        }

        location /b {
            js_content main.b;
        }
    }
}
