daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    upstream backend {
        server 127.0.0.1:8080;
    }

    server {
        listen 8888;

        location / {
            js_content main.resolv;
        }

        location /proxy {
            internal;
            proxy_pass http://backend;
        }
    }

    server {
        listen 8080;
        location / {
            return 200 "$request_uri";
        }
    }

    server {
        listen 8090;

        location = /map {
            js_content main.map;
        }

        location = /add {
            js_content main.add;
        }

        location = /remove {
            js_content main.remove;
        }
    }
}
