daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";
    js_import main from app.js;

    js_var $meta_name;
    js_var $meta_version;
    js_var $other_flag;

    server {
        listen 8888;

        location /all {
            js_content main.all;
        }

        location /prefix {
            js_content main.by_prefix;
        }

        location /no-match {
            js_content main.no_match;
        }
    }
}

stream {
    js_engine qjs;
    js_path "njs/";
    js_import main from app.js;

    js_var $s_alpha;
    js_var $s_beta;
    js_var $s_gamma;

    js_set $stream_all main.stream_all;
    js_set $stream_prefix main.stream_prefix;

    server {
        listen 8889;
        return $stream_all;
    }

    server {
        listen 8890;
        return $stream_prefix;
    }
}
