daemon off;
events {  }

http {
    error_log logs/error.log debug;
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    resolver 1.1.1.1 ipv6=off;

    server {
        listen 8888;

        location / {
            js_content main.fetch;
            js_fetch_trusted_certificate "../../submodules/njs-examples/njs/http/certs/ISRG_Root_X1.pem";
        }

    }
}
