daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}


http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    server {
        listen 8888;

        location /encrypt {
            js_content main.encrypt;
        }

        location /decrypt {
            js_content main.decrypt;
        }

    }
}
