
events {
    worker_connections 64;
}

stream {
    error_log logs/error.log debug;
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    js_shared_dict_zone zone=stream_detect_http:1m type=string timeout=60s;

    js_set $upstream main.upstream_type;

    upstream httpback {
        server 127.0.0.1:8080;
    }

    upstream tcpback {
        server 127.0.0.1:3001;
    }

    server {
        listen 8888;

        js_preread main.detect_http;

        proxy_pass $upstream;
    }

    server {
        listen 3001;

        return "TCPBACK\n";
    }

}

http {
    server {
        listen 8080;

        location / {
            return 200 "HTTPBACK";
        }

    }
}
