daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    server {
        listen 8888;

        location /join {
            js_content main.join;
        }

        location /foo {
            proxy_pass http://localhost:8080;
        }

        location /bar {
            proxy_pass http://localhost:8090;
        }

    }

    server {
        listen 8080;

        location / {
            return 200 "FOO";
        }

    }

    server {
        listen 8090;

        location / {
            return 200 "BAR";
        }

    }
}
