daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";
    js_import main from app.js;

    js_var $body_echo;

    server {
        listen 8888;

        location /text {
            js_access main.store_text;
            js_content main.echo_body;
        }

        location /buffer {
            js_access main.store_buffer;
            js_content main.echo_body;
        }

        location /json {
            js_access main.store_json;
            js_content main.echo_body;
        }

        location /decline {
            js_access main.just_decline;
            return 200 "passed\n";
        }
    }
}
