
daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    upstream backend_a {
        server 127.0.0.1:8081;
    }

    upstream backend_b {
        server 127.0.0.1:8082;
    }

    server {
        listen 8888;

        js_set $backend main.backend_var;

        location /secure/ {
            proxy_pass http://$backend;
        }
    }

    server {
        listen 127.0.0.1:8081;
        return 200 "BACKEND A:$uri\n";
    }

    server {
        listen 127.0.0.1:8082;
        return 200 "BACKEND B:$uri\n";
    }
}
