daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    server {
        listen 8888;

        location / {
            js_body_filter main.to_lower_case;
            proxy_pass http://127.0.0.1:8889;
        }

        location /long {
            js_body_filter main.to_lower_case;
            proxy_pass http://127.0.0.1:8889/long;
        }
    }

    server {
        listen 8889;

        location / {
            return 200 'Hello World';
        }

        location /long {
            return 200 'The Quick Brown Fox Jumps Over The Lazy Dog. ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz 0123456789 MiXeD CaSe TeXt HeRe!';
        }
    }
}
