daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    server {
        listen 8888;

        location /modify_cookies {
            js_header_filter main.cookies_filter;
            proxy_pass http://127.0.0.1:8889;
        }
    }

    server {
        listen 8889;

        location /modify_cookies {
            add_header Set-Cookie "XXXXXX";
            add_header Set-Cookie "BB";
            add_header Set-Cookie "YYYYYYY";
            return 200 'OK';
        }
    }
}
