daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    js_set $jwt_payload_sub main.jwt_payload_sub;

    server {
        listen 8888;

        location /jwt {
            return 200 "$jwt_payload_sub";
        }
    }
}
