daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";
    js_import main from app.js;

    server {
        listen 8888;

        location /urlencoded {
            js_content main.urlencoded;
        }

        location /multipart {
            js_content main.multipart;
        }

        location /max-keys {
            js_content main.max_keys;
        }
    }
}
