daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    server {
        listen 8888;

        location / {
            js_content main.chain;
        }

        location /step1 {
            js_content main.step1;
        }

        location /step2 {
            js_content main.step2;
        }
    }
}
