import njs/ngx

pub fn module_test() {
  let _ = ngx.object
  let _ = ngx.merge
  let _ = ngx.now
  let _ = ngx.append
  let _ = ngx.to_json
  let _ = ngx.to_string
  let _ = ngx.make_array
  let _ = ngx.get
  let _ = ngx.name
  let _ = ngx.fetch_url
  let _ = ngx.fetch_request
  let _ = ngx.atob
  let _ = ngx.btoa
  let _ = ngx.base64url_decode
  let _ = ngx.base64url_encode
  let _ = ngx.log
  let _ = ngx.build
  let _ = ngx.conf_file_path
  let _ = ngx.conf_prefix
  let _ = ngx.error_log_path
  let _ = ngx.prefix
  let _ = ngx.nginx_version
  let _ = ngx.ngx_version_number
  let _ = ngx.worker_id
  let _ = ngx.level_err
  let _ = ngx.level_info
  let _ = ngx.level_warn
  let _ = ngx.engine_id
  let _ = ngx.njs_version
  let _ = ngx.njs_version_number
  let _ = ngx.njs_engine
  let _ = ngx.njs_on
  let _ = ngx.version
  let _ = ngx.parse_query_string
  let _ = ngx.make_query_string
}
