daemon off;
error_log logs/error.log debug;
events {  }

stream {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    server {
        listen 8888;

        proxy_pass 127.0.0.1:8080;
        js_filter main.inject_foo_header;
    }

}

http {
    server {
        listen 8080;

        location / {
            return 200 "${http_foo}\n";
        }

    }
}
