daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    js_shared_dict_zone zone=requests:1M type=number;

    js_set $num_requests main.num_requests;

    log_format custom '$remote_addr [$time_local] requests=$num_requests';
    access_log logs/access.log custom;

    server {
        listen 8888;

        location / {
            return 200 "Request count: $num_requests\n";
        }

        location /count {
            return 200 "$num_requests";
        }
    }
}
