daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    keyval_zone zone=foo:10m;

    server {
        listen 8888;

        location /keyval {
            js_content main.set_keyval;
        }
    }
}
