daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    js_shared_dict_zone zone=kv:1M type=string timeout=3600s evict;

    server {
        listen 8888;

        location /keyval {
            js_content main.set_keyval;
        }

        location /get {
            js_content main.set_keyval;
        }
    }
}
