daemon off;
error_log logs/error.log debug;
pid logs/nginx.pid;

events {
    worker_connections 64;
}

http {
    js_engine qjs;
    js_path "njs/";

    js_import main from app.js;

    js_set $dec_foo main.dec_foo;

    server {
        listen 8888;

        location /version {
            js_content utils.version;
        }

        location /foo {
            return 200 "$arg_foo";
        }

        location /dec_foo {
            return 200 "$dec_foo";
        }
    }
}
